language: julia
julia:
  - release
notifications:
  email: false
scripts:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Fixed_point"); Pkg.test("Fixed_point"; coverage=true)';
